(() => {
  const API="https://api.tfl.gov.uk",results=document.querySelector("#disruptionResults"),refreshButton=document.querySelector("#refreshDisruptions"),themeButton=document.querySelector("#themeButton"),searchInput=document.querySelector("#disruptionSearch"),disruptedOnly=document.querySelector("#disruptedOnly"),tabs=[...document.querySelectorAll(".mode-tab")];
  let activeMode="all",services=[],selectedKey="",query="",onlyDisrupted=false;
  const escapeHtml=(value="")=>String(value).replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"})[c]);
  const apiUrl=path=>{const key=window.APP_CONFIG?.tflApiKey?.trim(),separator=path.includes("?")?"&":"?";return `${API}${path}${key?`${separator}app_key=${encodeURIComponent(key)}`:""}`};
  const fetchJson=async path=>{const response=await fetch(apiUrl(path));if(!response.ok)throw new Error(`TfL request failed (${response.status})`);return response.json()};
  const modeLabel=mode=>({bus:"Bus",tube:"Tube",overground:"London Overground","elizabeth-line":"Elizabeth line",dlr:"DLR",tram:"Tram","river-bus":"River"})[mode]||mode;
  const routeSort=(a,b)=>String(a.name).localeCompare(String(b.name),"en-GB",{numeric:true}),serviceKey=service=>`${service.mode}:${service.name}`;
  function extractBusRoutes(disruption){const values=new Set(),add=value=>{const text=String(value||"").trim();if(text&&/^[A-Z]*\d+[A-Z]*$/i.test(text))values.add(text.toUpperCase())};(disruption.affectedRoutes||[]).forEach(route=>add(route.name||route.lineId||route.routeId));(disruption.routeSectionNaptanEntrySequence||[]).forEach(section=>{add(section.lineId);add(section.routeId);String(section.lineString||"").split(/[,/ ]+/).forEach(add)});String(disruption.description||disruption.summary||"").match(/\b(?:N|X|SL)?\d{1,3}[A-Z]?\b/gi)?.forEach(add);return [...values]}
  function detailCard(service){const disruptions=service.disruptions||[];if(!disruptions.length)return `<section class="selected-disruption good-detail"><div><p class="eyebrow">${escapeHtml(modeLabel(service.mode))}</p><h3>${escapeHtml(service.name)}</h3></div><span class="service-ok">✓ Good service</span><p>TfL is not currently reporting a disruption for this service.</p></section>`;return `<section class="selected-disruption alert-detail"><div class="selected-heading"><div><p class="eyebrow">${escapeHtml(modeLabel(service.mode))}</p><h3>${escapeHtml(service.name)}</h3></div><span class="alert-count">! ${disruptions.length}</span></div>${disruptions.map(item=>`<article class="disruption-detail-item"><strong>${escapeHtml(item.severity||"Service disruption")}</strong><p>${escapeHtml(item.description||"No further details supplied by TfL.")}</p></article>`).join("")}</section>`}
  function render(){let filtered=activeMode==="all"?services:services.filter(service=>service.mode===activeMode);if(query)filtered=filtered.filter(service=>`${service.name} ${modeLabel(service.mode)}`.toLowerCase().includes(query));if(onlyDisrupted)filtered=filtered.filter(service=>service.disruptions.length);filtered.sort(routeSort);if(!filtered.length){results.className="good-service";results.innerHTML=`<strong>No matching services</strong><p>Try changing the search, mode or disruption-only filter.</p>`;return}if(!filtered.some(service=>serviceKey(service)===selectedKey))selectedKey="";const disruptedCount=filtered.filter(service=>service.disruptions.length).length;results.className="live-card-body";results.innerHTML=`<div class="status-summary"><strong>${disruptedCount}</strong> of ${filtered.length} shown services currently have reported disruptions.</div><div class="route-status-grid" aria-label="Route disruption status">${filtered.map(service=>{const disrupted=service.disruptions.length>0,key=serviceKey(service);return `<button class="route-status-tile ${disrupted?"has-disruption":"no-disruption"}${key===selectedKey?" selected":""}" type="button" data-key="${escapeHtml(key)}" aria-expanded="${key===selectedKey}"><span class="route-status-name">${escapeHtml(service.name)}</span><span class="route-status-icon" aria-hidden="true">${disrupted?"!":"✓"}</span><span class="sr-only">${disrupted?`${service.disruptions.length} disruptions`:"No disruption"}</span></button>`}).join("")}</div><div id="selectedDisruption" aria-live="polite">${selectedKey?detailCard(filtered.find(service=>serviceKey(service)===selectedKey)):""}</div>`;results.querySelectorAll(".route-status-tile").forEach(button=>button.addEventListener("click",()=>{selectedKey=selectedKey===button.dataset.key?"":button.dataset.key;render();document.querySelector("#selectedDisruption")?.scrollIntoView({behavior:"smooth",block:"nearest"})}))}
  function railServices(lines,mode){return lines.map(line=>({mode,name:line.name||modeLabel(mode),disruptions:(line.lineStatuses||[]).filter(status=>Number(status.statusSeverity)!==10).map(status=>({severity:status.statusSeverityDescription,description:status.reason||status.disruption?.description||status.statusSeverityDescription}))}))}
  async function loadBusServices(){const [routeDatabase,disruptions]=await Promise.all([fetch("data/routes.json").then(response=>{if(!response.ok)throw new Error("Route database could not be loaded");return response.json()}),fetchJson("/Line/Mode/bus/Disruption").catch(()=>[])]),disruptionMap=new Map();disruptions.forEach(disruption=>extractBusRoutes(disruption).forEach(route=>{if(!disruptionMap.has(route))disruptionMap.set(route,[]);disruptionMap.get(route).push({severity:disruption.severityDescription||disruption.categoryDescription||"Bus disruption",description:disruption.description||disruption.summary||"Bus disruption reported by TfL."})}));return (routeDatabase.current||[]).map(route=>{const name=String(route.Route||"").toUpperCase();return {mode:"bus",name,disruptions:disruptionMap.get(name)||[]}}).filter(service=>service.name)}
  async function loadDisruptions(){results.className="status-text live-card-body";results.textContent="Loading every route and current service status…";refreshButton.disabled=true;try{const railModes=["tube","overground","elizabeth-line","dlr","tram","river-bus"],data=await Promise.all([...railModes.map(mode=>fetchJson(`/Line/Mode/${mode}/Status?detail=true`).then(lines=>railServices(lines,mode))),loadBusServices()]);services=data.flat();render()}catch(error){results.className="good-service";results.innerHTML=`<strong>Disruptions could not be loaded</strong><p>${escapeHtml(error.message)}</p>`}finally{refreshButton.disabled=false}}
  tabs.forEach(tab=>tab.addEventListener("click",()=>{activeMode=tab.dataset.mode;selectedKey="";tabs.forEach(item=>item.classList.toggle("active",item===tab));render()}));searchInput.addEventListener("input",()=>{query=searchInput.value.trim().toLowerCase();selectedKey="";render()});disruptedOnly.addEventListener("change",()=>{onlyDisrupted=disruptedOnly.checked;selectedKey="";render()});refreshButton.addEventListener("click",loadDisruptions);
  const applyTheme=dark=>{document.body.classList.toggle("dark",dark);themeButton.textContent=dark?"Light mode":"Dark mode"};applyTheme(localStorage.getItem("rfl-theme")==="dark");themeButton.addEventListener("click",()=>{const dark=!document.body.classList.contains("dark");localStorage.setItem("rfl-theme",dark?"dark":"light");applyTheme(dark)});loadDisruptions();setInterval(loadDisruptions,120000);
})();